import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { SosProvider } from "@/components/context/SosContext";
import { ZerodhaProvider } from "@/components/context/ZerodhaContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Phantom Link",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider publishableKey="pk_test_ZGVzaXJlZC1mb3dsLTkyLmNsZXJrLmFjY291bnRzLmRldiQ">
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SosProvider>
            <ZerodhaProvider>{children}</ZerodhaProvider>
          </SosProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
